/**
 * Existing Actions
 */
export const USER_START = 'USER_START'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FLAT_POSTS_SUCCESS = 'USER_FLAT_POSTS_SUCCESS'
export const USER_ERROR = 'USER_ERROR'
export const USER_COMMENT = 'USER_COMMENT'

/**
 * Post Action Types
 */
export const POST_START = 'POST_START'
export const POST_SUCCESS = 'POST_SUCCESS'
export const POST_SUBJECT_SUCCESS = 'POST_SUBJECT_SUCCESS'
export const POST_COMMENT_SUBMIT = 'POST_COMMENT_SUBMIT'
export const POST_END = 'POST_END'
export const POST_ERROR = 'POST_ERROR'
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const CREATE_MAIN_POST_SUCCESS = 'CREATE_MAIN_POST_SUCCESS'

/**
 * User Action Types
 */
export const USER_OPETATION_START = 'USER_OPETATION_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_OPERATION_FAILED = 'USER_OPERATION_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_EMAIL_CONFIRM_SUCCESS = 'USER_EMAIL_CONFIRM_SUCCESS'
export const USER_RESTORE_SUCCESS = 'USER_RESTORE_SUCCESS'
export const USER_EMAIL_CONFIRM_SENDED = 'USER_EMAIL_CONFIRM_SENDED'
export const USER_SEND_FORGET_PASSWORD_DETAILS = 'USER_SEND_FORGET_PASSWORD_DETAILS'

/**
 * Comment Action Types
 */

export const COMMENT_OPETATION_START = 'COMMENT_OPETATION_START'
export const COMMENT_OPERATION_FAILED = 'COMMENT_OPERATION_FAILED'
export const COMMENT_CREATED_SUCCESS = 'COMMENT_CREATED_SUCCESS'

/**
 * Tree Action Types
 */

export const TREE_OPETATION_START = 'TREE_OPETATION_START'
export const TREE_OPERATION_FAILED = 'TREE_OPERATION_FAILED'
export const TREE_FETCH_SUBJECT_NAME_SUCCESS = 'TREE_FETCH_SUBJECT_NAME_SUCCESS'
export const TREE_UPDATE_SUBJECT_NAME_SUCCESS = 'TREE_UPDATE_SUBJECT_NAME_SUCCESS'
export const TREE_FETCH_PARENT_ID_SUCCESS = 'TREE_FETCH_PARENT_ID_SUCCESS'
export const TREE_SUBJECT_MOVE__SUCCESS = 'TREE_SUBJECT_MOVE__SUCCESS'
export const TREE_CREATE_NEW_POST_SUCCESS = 'TREE_CREATE_NEW_POST_SUCCESS'

/**
 * Admin Action Types
 */

export const ADMIN_OPETATION_START = 'ADMIN_OPETATION_START'
export const ADMIN_OPETATION_SUCCESS = 'ADMIN_OPETATION_SUCCESS'
export const ADMIN_OPERATION_FAILED = 'ADMIN_OPERATION_FAILED'
